### ISSUE TITLE
New Babylon version / Update NPM

### ISSUE THREAD

**Issue by RaananW** [jakubbilko/generator-babylon#3]
Hi, 
Thanks for a great generator!
The NPM version of this generator and this version are not the same (babylon.js is being served there, whereas here it is being included as an NPM dependency).
Also, there is a new BabylonJS version :smile:

I was actually planning to create a new generator for BabylonJS, including typescript support etc', but saw that there is already one. Will you continue updating this generator?

**Comment by jakubbilko** [comment]
Hi,
I don't really have much time to contribute to this project as much as I would want to. If you're interested in taking over/contributing, I will be glad to add you as a contributor. I won't lie, there's a lot of work to be done here, but maybe it'll give me some motivation to work on it ;)

**Comment by RaananW** [comment]
Hi,
I can totally understand the no-time factor :)
Will be great to take over (if you don't want to do it anymore) or join as a contributor. My time is also (sadly :smile:) limited, but I think this is a wonderful way to start a BJS project.

**Comment by RaananW** [comment]
fixed with this PR - https://github.com/jakubbilko/generator-babylon/pull/4
